language: node_js
node_js:
  - '10'
deploy:
  provider: heroku
  api_key:
    secure: X7iBkfm3GhUFoT7Ylwlj8+FQP2yMPrAKwWTd7h2tOoSnuNEfaJHLug0MpeDQOfGUGNiwY4YXcAb+naWHanakExUVlTeSnlsVZHhfkpJefeOihiOIXCEacgLaCGtLnQZ/yLjjwq/q7FiXMfXz5TVVO9dmBFsoDaiXs/KCsjQ/7etxwLqwQmCrgfburQbwkYKwPBbvdymddKnYqoTFTBnHGNIm13El1jqNjKEDLpgvZfib5B3NbP3N1HLeCKUhHjPtygYUMB8c6/q9oiTrKjQnndU3Bb36wJr0LjfuPbezZfItaPnYnkGM/8Tc18gu3CDhK5Rg90SXXAjLj8GIq7XEIkQOz06hVjlbGD6r8gGIXedBgulM8HvExmsbPTWfSwzgKJHRD/bD6JXqGLbZEFZoy+lVUFg/yCXDvMtmTAVLYW+wsjqWZYinFEqOfLolmHTI1dYWmAdZTqxqb5t2QvQjoEq1tI7JVsyWmuBP9g84kIqxrwHFC9QqYDpzE117RnHyfPnVdbZyyQZcGBKlknzWh7RJ08ju16bsR7RuFBqFyFoYZTx7ps0xumf6rdyO65Y/NMm6vnuYee6mGpX8mSSqeWhYb6k1PLhOfDDOUpG78YtIV6YAUQf+d0TKK+evph+iyIPdrVQ9abLtWLSwdk2QIBY2HJKedHSdgvV2lUI0CXU=
  app:
    master: sftennis2017
notifications:
  email:
    recipients:
      - trebek08@gmail.com
    on_success: change
    on_failure: always
