// flow-typed signature: e34660f5fa31e29954eddf4a014c1fd5
// flow-typed version: <<STUB>>/font-awesome-loader_v^1.0.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'font-awesome-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'font-awesome-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'font-awesome-loader/font-awesome-styles.loader' {
  declare module.exports: any;
}

declare module 'font-awesome-loader/font-awesome.config' {
  declare module.exports: any;
}

declare module 'font-awesome-loader/index.loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'font-awesome-loader/font-awesome-styles.loader.js' {
  declare module.exports: $Exports<'font-awesome-loader/font-awesome-styles.loader'>;
}
declare module 'font-awesome-loader/font-awesome.config.js' {
  declare module.exports: $Exports<'font-awesome-loader/font-awesome.config'>;
}
declare module 'font-awesome-loader/index' {
  declare module.exports: $Exports<'font-awesome-loader'>;
}
declare module 'font-awesome-loader/index.js' {
  declare module.exports: $Exports<'font-awesome-loader'>;
}
declare module 'font-awesome-loader/index.loader.js' {
  declare module.exports: $Exports<'font-awesome-loader/index.loader'>;
}
